### ISSUE TITLE
Security update needed

### ISSUE THREAD

**Issue by sstruble** [DSNP-org/dsnp-org.github.io#37]
https://github.com/TryGhost/Ghost/security/advisories/GHSA-65p7-pjj8-ggmr

**Comment by claireolmstead** [comment]
@sstruble we do not have ghost installed because we're using gatsby and gatsby-source-ghost to pull data in from ghost.  Because of this I don't think this vulnerability applies to us.  Let me know if there is something that I'm missing!

**Comment by sstruble** [comment]
ok! I get 'critical security update available' every time I log into the Ghost CMS for DSNP.org, but if it doesn't actually affect us, I'll ignore it. Thanks for looking at this.
