### ISSUE TITLE
Update DSNP.org dev portal: Code of Conduct 

### ISSUE THREAD

**Issue by sstruble** [DSNP-org/dsnp-org.github.io#40]
Update the dev portal navigation sidebar for clarity and new material

- Expand "Conduct" in left sidebar navigation to Code of Conduct. If template doesn't permit that many characters, then ignore this.
- Page content should be just https://www.dsnp.org/code-of-conduct
- Remove Security Vulnerabilities 
- Remove Contribution Guidelines

**Comment by claireolmstead** [comment]
Changed in favor of linking directly to
