### ISSUE TITLE
Revise DSNP home page design 

### ISSUE THREAD

**Issue by sstruble** [DSNP-org/dsnp-org.github.io#44]
Revise DSNP.org home page design to be clearer about calls-to-action

Replace current boxes at bottom with new design and three new static boxes: **Learn, Build, Create** 

Content for Learn: 
Text: Curious to learn more about DSNP, the new foundational technology for a better Web? 
(and include link to https://www.dsnp.org/about-what-is-dsnp)

Content for Build: 
Text: Build innovative new apps and services with DSNP
(and include link to https://www.dsnp.org/developer-portal/)

Content for Create: 
Text: Join a community that’s building a new civic architecture for the digital world.
(and include link to Contribute + Community page - https://www.dsnp.org/dev-portal-community at the moment)

**Comment by claireolmstead** [comment]
On pause for future designs and content.

**Comment by claireolmstead** [comment]
Redesigned with an outside agency.
